# Arrays in python
An object that stores a group of element of same datatypes
Numpy

In [1]:
! pip install numpy

You should consider upgrading via the 'c:\users\tanis\anaconda3\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy

In [3]:
arr = numpy.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [4]:
type(arr)

numpy.ndarray

In [5]:
from numpy import *
a = array([1,2,3,4,5])
b = array(a)
c = a

In [6]:
print(a)
print(b)
print(c)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


## Creating array using linespace


In [8]:
a = linspace(0,100,50)
print(a)

[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


## Creating array using arange() Funtion

In [9]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arange(5,10)

array([5, 6, 7, 8, 9])

In [12]:
#zeros(n, datatype)
#ones(n, datatypes)
#eye
zeros(5,int)

array([0, 0, 0, 0, 0])

In [14]:
eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
#check if 2 arrays are equal
a = array([1,2,3,4,5])
b = array([0,1,2,3,4,5])
print(a == b)

False
<ipython-input-16-0485a3e20915>:4: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(a == b)


In [17]:
#slicing
a = array([10,20,30,40,50,60])
a

array([10, 20, 30, 40, 50, 60])

In [19]:
a[1:6:2]

array([20, 40, 60])

In [20]:
a.shape

(6,)

In [22]:
a = array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [24]:
a = array([10,20,30,40,50,60])
a.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [25]:
a.max()

60

In [26]:
a.min()

10

In [27]:
a.mean()

35.0

In [28]:
sum(a)

210

In [29]:
a.mean()

35.0

In [30]:
a = array([10,20,80,40,50,60])
a.sort()

In [31]:
a

array([10, 20, 40, 50, 60, 80])

In [32]:
random.rand()

0.10879705982728682

In [33]:
a = random.rand(5)

In [34]:
a



array([0.18795861, 0.42311366, 0.03315272, 0.42903753, 0.42725615])

In [35]:
type(a)

numpy.ndarray